# Generated by Django 2.2.9 on 2020-07-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '5605_searchexporthistory_downloadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptEditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edittype', models.TextField(blank=True, null=True)),
                ('conceptid', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('userid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concept_edit_log',
                'managed': True,
            },
        ),
    ]
