# Generated by Django 2.2.9 on 2020-07-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '5606_concepteditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepteditlog',
            name='userid',
        ),
    ]
