# Generated by Django 2.2.24 on 2022-10-31 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '7128_resource_instance_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestResourceEdit',
            fields=[
                ('editlogid', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('resourcedisplayname', models.TextField(blank=True, null=True)),
                ('resourceinstanceid', models.TextField(blank=True, null=True)),
                ('edittype', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'latest_resource_edit',
                'managed': True,
            },
        ),
    ]
